### ISSUE TITLE
How to set Auth?

### ISSUE THREAD

**Issue by elongstreet88** [kthrdei/snmp-agent#4]
Is there a way to set the auth on this?
I've been trying to figure out how to set it, but cannot get it working.

Example: V2 with community string "public".

Thanks!

**Comment by kthrdei** [comment]
You can add a community check at the beginning of the handler.
```
async def handler(req: snmp_agent.SNMPRequest) -> snmp_agent.SNMPResponse:
    if req.community != "public":
        raise Exception

    vbs = ...
```
